
## Defined Learning - Terms of Use - Open Source Policies
### (A) Use of the Website
       (a) The website (hereinafter "Website") is owned and operated by Defined Learning,. Unless otherwise indicated, the content, format and imagery of the Website are copyrighted under the laws of the United States by Defined Learning, and are protected by worldwide copyright laws and treaty provisions. Unauthorized duplication is a violation of law. The content, format and imagery of the Website may not be copied, published, broadcast, distributed, reproduced or transmitted in any way. You may not use the Website or any materials on the Website in any commercial or for-profit manner.
       (b) For purposes of this Agreement, the use of any materials from the Website on any other website or computer environment is prohibited without the express written consent of Defined Learning For the purpose of the Terms of Use the term "Subscriber" shall apply to those users of the Website who are registered subscribers that have a valid user name and password for accessing the Website and the material on the Website. 
### (B) Confidentiality 
In consideration of the Website and any services provided by Defined Learning in connection therewith (hereafter, the "Service"), Subscribers agree to: keep their user name and password confidential. Each Subscriber is responsible for maintaining the security and confidentiality of all log-In information, including user name and password information. 
### (C) Use of the Material 
Defined Learning reserves the right, in its sole discretion, to limit any SubscriberÕs use of the Website in the event that Defined Learning, in its sole discretion, deems such SubscriberÕs use of the Website to be inconsistent with noncommercial, educational purposes and/or inconsistent with the Terms of Use. 

		(a) The Website and the images, audio files and video files on the Website ("Material") are owned or licensed by Defined Learning and are protected by United States and international copyright, trademark and other intellectual property laws. Subscriber does not gain any type of ownership interest in the Website or the Material by using the Website or the Material.

		(b) Subscriber may download, solely in connection with noncommercial educational use, copies of the Material designated on the Website as "Downloadable." Copies of downloaded Material must be deleted or erased after use or expiration of the Term, whichever occurs first. Any and all downloading shall be for individual Subscriber convenience only, and Subscribers may not (i) systematically download any of the Material; (ii) create distribution libraries from the Material; or (iii) sell, rent, display, exhibit or otherwise transfer any of the Material to any third party outside of the SubscriberÕs classroom.

		(c) In the course of using any Material as permitted hereunder, Subscriber may not make the Material, or any part thereof, available to any party who is not a Subscriber, except as permitted herein. Subscriber must ensure that the Material is at all times kept on a secure server, viewable only by Subscribers. If Subscriber wishes to use a third party to host the Material, Defined Learning must pre-approve the use of such proposed host in writing prior to use of the proposed host. Defined Learning shall have the right to approve the terms of the proposed agreement between the proposed host and Subscriber. Except as expressly set forth herein, Subscriber may not:
	   
			(i) copy, modify, transmit, perform,create derivative works of, publish, sub-license, or otherwise share the Website, the Material, or any portion thereof; 
			(ii) disassemble, reverse engineer or decompile the Website or any portion thereof; 
			(iii) use any "deep-link", "page-scrape", "robot", "spider," "offline readers," or any equivalent manual process, to access or monitor any portion of the Website; 
			(iv) collect any personally identifiable information, including user names or passwords, from the Website; 
			(v) take any actions that may circumvent, disable or damage the Website's security; 
			(vi) use the Material in a manner that disparages the Website, Defined Learning, or the Material; or 
			(vii) use the Material or Website in any manner that Defined Learning may, in its sole and exclusive discretion, deem inappropriate. 
			
		(d) Subscriber understands and agrees that the Website and the Material possess a unique character that makes it difficult to assess the monetary damages that would be sustained as a result of unauthorized use of the Website or Material. Subscriber understands and agrees that unauthorized use may cause immediate and irreparable damage to Defined Learning for which Defined Learning would not have an adequate remedy at law. Therefore, Subscriber agrees that, in the event of such unauthorized use, in addition to such other legal and equitable rights and remedies that may be available to Defined Learning, shall be entitled to injunctive and other equitable relief without the necessity of proving damages or furnishing a bond or other security. 
		
### (D) Actions as a Subscriber 
Subscriber acknowledge and understand that all information, data, text, software, music, sound, photographs, graphics, video, messages, content or other submissions ("Submission"), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Materials originated.

		(a) Subscriber agree not to use the Website to:
			(i) upload, post, email or otherwise transmit any Submission that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful whether sexually, racially or ethnically, or otherwise objectionable; 
			(ii) harm minors in any way; 
			(iii) impersonate any person or entity, including, but not limited to, any law enforcement officer, or any Defined Learning official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity; 
			(iv) forge headers or otherwise manipulate identifiers in order to disguise the origin of any Submission transmitted through the Website; 
			(v) upload, post, email or otherwise transmit any Submission that you do not have a right to transmit under any law or under contractual or fiduciary relationship (such as inside information, proprietary and confidential information learned or disclosed as part of an employment relationship or under any nondisclosure agreement); 
			(vi) upload, post, email or otherwise transmit any Submission that infringes, contributes to the infringement of, or induces others to infringe, any patent, trademark, trade secret, copyright or other proprietary rights of any party; 
			(vii) upload, post, email or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation. 
			(viii) upload, post, email or otherwise transmit anything that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment or in any other way cause damage to a user's data against the will of the user; 
			(ix) disrupt the normal flow of dialogue, cause a screen to "scroll" faster than other users of the Website are able to type, or otherwise act in a manner that negatively affects other users' ability to engage in real-time exchanges; interfere with or disrupt the Website or servers or networks connected to the Website, or disobey any requirements, procedures, policies or regulations of networks connected to the Website; intentionally or unintentionally violate any applicable local, state, national or international law, any rules of any national or other securities exchange, and any regulations having the force of law; 
			(x) "stalk" or otherwise harass another; or collect or store personal data about other users. 
			(xi) Subscriber acknowledges that Defined Learning and anyone it designates shall have the right, but not the obligation, in their sole discretion to move or refuse to move any Submission that is available via the Website. Without limiting the foregoing, Defined Learning and anyone it designates shall have the right to remove any Submission that violates these terms of use or are otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Submission, including any reliance on the accuracy, completeness, or usefulness of such Submission. In this regard, you acknowledge that you may not rely on any Content 
				(1) created by Defined Learning or on the Website, or 
				(2) submitted to Defined Learning or the Website, including without limitation information in any Defined Learning bulletin boards and in all other parts of the Website. 

		(b) Subscriber acknowledges and agree that Defined Learning and the Website may preserve any Submission and may also disclose any Submission if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: 
			(i) comply with legal process; 
			(ii) enforce these terms of service; 
			(iii) respond to claims that any Content violate the rights of third-parties; or 
			(iv) protect the rights, property, or personal safety of Defined Learning and the Website, its users and the public. 
		
		(c) Subscriber understands that the technical processing and transmission of the Website, including your Submission, may involve 
			(i) transmissions over various networks; and 
			(ii) changes to conform and adapt to technical requirements of various networks or devices to which the Website is connected. 
		
		(d) The Website contains robot exclusion headers and you agree that you will not use any robot, spider, other automatic device, or manual process to monitor or copy our web pages or the content contained herein without our prior expressed written permission. You agree that you will not use any device, software or routine to bypass our robot exclusion headers, or to interfere or attempt to interfere with the proper working of the Defined Learning site or any activities conducted on our site. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on our infrastructure. Much of the information on our site is updated on a real time basis and is proprietary or is licensed to Defined Learning or its vendors or third parties. You agree that you will not copy, reproduce, alter, modify, create derivative works, or publicly display any content from the Website without the prior expressed written permission of Defined Learning, or the appropriate third party. 

### (E) Correction of Errors and Inaccuracies 
The content of the Website, including but not limited to text, availability and descriptions may contain errors or inaccuracies, and may not be complete or current. Defined Learning reserves the right to correct any errors, inaccuracies or omissions and to change or update information at any time without prior notice. We apologize for any inconvenience this may cause you. 
### (F) Termination 
If in the event a user or users infringes on any third party's rights, or engage in conduct that is illegal, tortuous or that interferes with the technological operation of this site, this Agreement is subject to termination by either party thirty (30) days after notification by letter prior to the end of the then-current contract year. If by the end of the 30 day period the conduct, infringement, or activity is rectified agreement will not be terminated. However, if conduct, infringement, or activity persists this agreement will be terminated and Subscriber must destroy all Materials obtained from Defined Learning or the Website and all copies thereof. 
### (G) Disclaimer 
Defined Learning MAKES, AND THE WEBSITE INCLUDES, NO REPRESENTATIONS OR WARRANTIES WITH RESPECT TO Defined Learning OR THE CONTENTS OF THE WEBSITE, INCLUDING THE MATERIAL, WHICH ARE PROVIDED FOR USE "AS IS" AND "AS AVAILABLE." Defined Learning AND THE WEBSITE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO Defined Learning AND THE WEBSITE AND ANY WEB SITE WITH WHICH IT IS LINKED OR CONTENT PROVIDED BY SUPPLIERS TO THE WEBSITE. Defined Learning DOES NOT WARRANT THE FUNCTIONS, INFORMATION OR LINKS CONTAINED ON OR THE WEBSITE OR THAT ITS CONTENTS WILL MEET YOUR REQUIREMENTS, THAT Defined Learning OR THE WEBSITE, OR ITS CONTENTS, ARE FIT FOR ANY PARTICULAR PURPOSE OR THAT THE OPERATION OF THE WEBSITE OR ITS CONTENTS, WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES, WORMS, TROJAN HORSES, CANCELBOTS OR OTHER HARMFUL COMPONENTS. Defined Learning DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE MATERIALS ON THE WEBSITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT Defined Learning OR THE WEBSITE) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. 
### (H) Limitation of Liability 
UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL Defined Learning OR THE WEBSITE BE LIABLE FOR ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF, OR THE INABILITY TO USE, THE MATERIALS ON THE WEBSITE, EVEN IF Defined Learning, OR AN AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN NO EVENT SHALL Defined Learning'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION (WHETHER IN CONTRACT, OR NOT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE WEBSITE. UNDER NO CIRCUMSTANCES SHALL Defined Learning BE RESPONSIBLE FOR ANY DAMAGES RELATED TO VIRUS INFECTION AND THE RESULTING CORRUPTION, DESTRUCTION, OR ALTERATION OF A USER OR SUPPLIER'S SYSTEM (INCLUDING FILES, SOFTWARE AND HARDWARE LOCATED ON THEIR SYSTEMS). 
### (I) Jurisdiction and Export 
The Website is controlled and operated by Defined Learning from its office in Deerfield, IL, United States of America. Defined Learning and the Website make no representation that materials on the Website are appropriate or available for use in other locations. Those who choose to access the Website from other locations do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. Data from this site is further subject to United States export controls. No software from Defined Learning or the Website may be downloaded or otherwise exported or re-exported into (or to a national or resident of (i) Cuba, Iran, Iraq, Libya, North Korea, Syria or any other country to which the United States has embargoed goods; or (ii) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Table of Deny Orders. By downloading or using the Data, you represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list. 

### (J). PRIVACY; PERSONAL INFORMATION AND STUDENT DATA
		(a) Privacy Policy. You understand that by using the Services you consent to the collection, use and disclosure of your personally identifiable information and aggregate and/or anonymized data as set forth in Defined Learnings' current privacy policy, which is available at https://www.definedstem.com/privacy (the "Privacy Policy") and is incorporated herein by this reference.

		(b) Student Data. To the extent that our Service is used by a College, University, local education agency, teacher, or other educational institution (“Educational Institution”) (a) and its students as part of school curriculum (e.g., a teacher training program in a University, or (b) by teachers as part of a teachers improvement program, the Personal Information we collect through the Service may include personal information from “educational records” as defined by the Family Educational Rights and Privacy Act (“FERPA”), 20 U.S.C. § 1232(g) (“Student Data”).

		(c) Confidentiality. Defined Learning agrees to treat Student Data as confidential and not to share it with third parties other than as described in these Terms, and in our Privacy Policy.

		(d) Student Data Access. To the extent that we collect Student Data through the provision of our Service, we may access, collect and process Student Data as a School Official with a legitimate educational interest pursuant to FERPA 34 CFR Part 99.31(a)(1). You agree that when Defined Learning is acting as a School Official, as between the parties, the Educational Institution or authorized User of that Educational Institution owns and controls all Student Data.

		(e) Personal Information and Student Data Consents and Authority. To the extent applicable, you represent and warrant that you have the requisite consent and authority to provide Student Data, to Defined Learning, or to authorize Defined Learning to collect Student Data through the Service. To the extent that Defined Learning collects Student Data, Defined Learning and the Educational Institution, each agree to uphold their responsibilities under laws governing Personal Information and Student Data, including in the U.S. the Family Educational Rights and Privacy Act (“FERPA”), the Protection of Pupil Rights Amendment (PPRA), and the Children’s Online Privacy and Protection Act (“COPPA”) and State laws, as applicable.

    (f) Personal Information of Non-Users, Which Could Include K12 Students. Through the course of providing our Services, it is possible that our Users submit User Submissions that contain personal information of individuals that are not Users of this Service and who are not covered under Agreements with Defined Learning. For example, if a User who is a student-teacher in a University program records video of her work in a classroom at a local K12 school, the video may contain images of children, teachers, or other individuals who are not covered by the Agreement between Defined Learning and the student-teacher’s University. To the extent that you provide personal information of non-users in User Submissions, including the personal information of K12 students, you represent and warrant that you comply with all the provisions of Section 3 User Submissions, above, and have all necessary rights to provide that information to Defined Learning. We rely on each User to ensure that appropriate disclosures and consents are obtained, if necessary, to provide content contained in User Submissions to Defined Learning.

    The Children’s Online Privacy and Protection Act (“COPPA”) requires that online service providers obtain parental consent before collecting personal information from children under 13. Defined Learning does not intentionally collect personal information from a child under 13. If you provide in User Content information collected from a student under 13, you represent and warrant that you are the student’s school or teacher and have received consent from parents, or have the authority to provide consent on behalf of parents, for us to collect information from the students before providing User Content of a child under 13 to our Service. We recommend that all schools and teachers provide appropriate disclosures to students and parents regarding their use of service providers such as Defined Learning and that they provide a copy of our Privacy Policy to parents and guardians.

		(g) User-Requested Third-Party Access. Defined Learning may provide users the ability to use and access third-party services through the Service, and to share data, including Student Data if applicable, with third-parties through the Service. If explicitly instructed by you, by the Educational Institution or by another User authorized to provide such consent, you agree to allow us to provide access to data, including Student Data, to third parties through the Service. You acknowledge that we are not responsible for the data practices of third parties with whom you or your authorized Users elect to share Student Data, and that, as between us, you are solely responsible for the consequences of providing or transmitting data, including Student Data, to such third parties through the Service.

		(h) Data Retention and Deletion Requests. You may request that we delete your personal information in our possession at any time as set forth in our Privacy Policy. If your account is utilizing a license provided by an Educational Institution or enterprise, the licensee may be required to authorize the deletion request. To contact us about deleting or de-identifying your account information, provide a written request to privacy@definedlearning.com, and we shall respond to the request within thirty (30) days. Notwithstanding the foregoing, we may not be able to delete all information contained on the Service, for example, if such information is part of another User’s User Submissions or content.

    (i) Data Localization. You acknowledge and agree that Defined Learning will store and process Personal Information in various data centers around the world, including in the U.S., and that your Personal Information may not be stored or processed only within the country in which it was collected unless and except to the extent required by Law. If you are an Educational Institution or teacher, you warrant and agree that you have obtained all necessary consents for Defined Learning to process such Personal Information in the U.S. and elsewhere in the world.

		(j) Security, Access and Support; Data Breach Notification. We have implemented commercially reasonable administrative, physical and technical safeguards designed to secure Personal Information, including Student Data, from unauthorized access, disclosure and use. In the event we have a reasonable, good faith belief that an unauthorized party has gained access to or been disclosed Student Data that we have collected or received through the Service, we will promptly notify the Educational Institution. If Personal Information, including Student Data, is acquired by an unauthorized party and such incident triggers any third-party notice requirements under applicable privacy laws, the Educational Institution shall be responsible for the timing, content and method of notice and for compliance with such laws for Users associated with the Educational Institution. Defined Learning shall be responsible for the timing, content, cost and method of notice and compliance with such laws as they relate to Users that are not associated with an Educational Institution.

    We will not be liable if for any reason the Service (or any part of it) is unavailable at any time or for any period. Additionally, access to the Service may be suspended temporarily and without notice in the case of system failure, maintenance or repair or for reasons beyond our control. Additionally, access to the internet, if employed, is your sole responsibility and the responsibility of the Internet provider(s) you select. Defined Learning does not accept any responsibility for failure of the Service due to Internet facilities
